trigger: none

resources:
  repositories:
    - repository: core--platform
      type: git
      name: Financial Service - Consulting/core--platform
      ref: main # versions/1.x.x

extends:
  template: core--devops-templates/python-lib.pipeline.yml@core--platform
